name: Test CI/CD

on:
  pull_request:
    branches:
      - master

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

  perform-ci-cd:
    runs-on: ubuntu-latest
    needs: setup-cache
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts --no-audit --prefer-offline

    - name: Run ESLint
      run: npx eslint $(git diff --relative --diff-filter=ACM --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | xargs)
      if: always()

    - name: Run Prettier
      run: npx prettier --check $(git diff --relative --diff-filter=ACM --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | xargs)
      if: always()

    - name: Run Jest
      run: npx jest
      if: always()
