name: Test CI/CD
'on':
  pull_request:
    branches:
      - master
      
jobs:
  perform-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          sparse-checkout: projects/test-this
      - run: git fetch origin
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Attempt to restore the cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: ./projects/test-this/node_modules
          key: '${{ runner.os }}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
        working-directory: ${{ github.workspace }}/projects/test-this
      - name: Install dependencies if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts --no-audit --prefer-offline --no-fund
      - name: Save the cache after installing dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ./projects/test-this/node_modules
          key: '${{ runner.os }}-node-${{ hashFiles(''**/package-lock.json'') }}'
        working-directory: ${{ github.workspace }}/projects/test-this
      - name: Run ESLint
        run: >-
          npx eslint $(git diff --relative --diff-filter=ACM --name-only ${{
          github.event.pull_request.base.sha }}..${{
          github.event.pull_request.head.sha }} | grep  -E '\.(js|jsx)$' |
          xargs)
        if: always()
      - name: Run Prettier
        run: >-
          npx prettier --check $(git diff --relative --diff-filter=ACM
          --name-only ${{ github.event.pull_request.base.sha }}..${{
          github.event.pull_request.head.sha }} | grep  -E
          '\.(js|jsx|mdx|scss)$' | xargs)
        if: always()
      - name: Run Jest
        run: npx jest
        if: always()
        working-directory: ${{ github.workspace }}/projects/test-this
