name: Test CI/CD

on: workflow_dispatch

jobs:
  setup-cache:
    runs-on: ubuntu-latest

  eslint:
    runs-on: ubuntu-latest
    needs: setup-cache

  jest:
    runs-on: ubuntu-latest
    needs: setup-cache

  prettier:
    runs-on: ubuntu-latest
    needs: setup-cache