name: Test CI/CD

on:
  pull_request:
    branches:
      - master

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

  perform-ci-cd:
    runs-on: ubuntu-latest
    needs: setup-cache
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - run: npm ci --no-audit --prefer-offline

    - run: npx eslint $(git diff --relative --diff-filter=ACM --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | xargs)

    - run: npx prettier --check $(git diff --relative --diff-filter=ACM --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | xargs)

    - run: npx jest
